### ISSUE TITLE
section缩进2字符的显示效果问题

### ISSUE THREAD

**Issue by 0shelter0** [xkwxdyy/CCNUthesis#11]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10

- TeX 发行版
  - [x] TeX Live 2022

- CCNUthesis发行版
  - [x] V1.2.13

## 描述问题

你好，现在还有个小问题，就是`section`缩进显示效果，如下图
![image](https://user-images.githubusercontent.com/38009361/229032625-53d32cd8-3b32-44d4-bd98-90f439a8eac5.png)

section `2.3`的缩进多了一丢丢，没有和下一段的开头第一个词完全对齐(即”原始“二字)。但是，subsection `2.3.1`和下一段的开头两个字完全可以对齐。然而，他们在样式设置中缩进的大小一致，如下代码所示，
```
section =
          {
            format      = \zihao{4} \sffamily \bfseries \raggedright,
            beforeskip  = 4.5 ex plus 1.0 ex minus 0.2 ex,
            afterskip   = 2.7 ex plus 0.5 ex,
            fixskip     = true,
            indent      = 2\ccwd
          },
        subsection =
          {
            format      = \zihao{-4} \sffamily \bfseries \raggedright,
            beforeskip  = 4 ex plus 1.0 ex minus 0.2 ex,
            afterskip   = 2.5 ex plus 0.3 ex,
            fixskip     = true,
            indent      = 2\ccwd
          },
```
他们的缩进都是`2\ccwd`，但是显示有点细微差别。不知道是不是我编译环境的影响。

**Comment by sikouhjw** [comment]
MWE:
```tex
\documentclass{ctexart}
\ctexset{
  section = {
    format = \zihao{4},
    indent = 2\ccwd,
  }
}
\begin{document}
\section{test}
test
\end{document}
```
问题在于：如果 `indent` 的值是以 `em`、`ex` 或 `\ccwd` 为单位，那么缩进间距的大小是相对于 `format` 中指定的字号大小。
![图片](https://user-images.githubusercontent.com/49770925/229046540-7a6f5b06-171a-430c-93e4-feed7706cfc3.png)

所以，解决方案：使用绝对距离，具体是多少？`zihao=-4` 时，一个字大小为 `12bp`，因此可以设置为 `24bp`。
```tex
\documentclass[zihao=-4]{ctexart}
\ctexset{
  section = {
    format = \zihao{4},
    indent = 24bp,
  }
}
\begin{document}
\section{test}
test
\end{document}
```

 @xkwxdyy 这里应该要改一下。当然，在 Word 中，所谓的『两个字符』间距也是由字体大小决定的，因此如果是为了『仿照 Word 的效果』，那就没必要修改。

**Comment by 0shelter0** [comment]
感谢大佬，经过设置绝对的`indent`之后，`section`的缩进可以准确显示了，如下：
![image](https://user-images.githubusercontent.com/38009361/229051288-6b3291bc-8518-46e0-8eb2-d7fdc3d5adcf.png)

**Comment by xkwxdyy** [comment]
> 这里应该要改一下。当然，在 Word 中，所谓的『两个字符』间距也是由字体大小决定的，因此如果是为了『仿照 Word 的效果』，那就没必要修改。

嗯嗯。主要是因为本科教务处的 word 的效果就是这样，我也没有过多处理，硕博的也没有对这方面有所要求。

**Comment by xkwxdyy** [comment]
我又去看了一下硕博的要求

```
博士学位论文正文内容为五号宋体，硕士学位论文正文内容为小四号宋体，段落按照“首行缩进”格式，每段开头空两个字符。一级标题另起一页，居中，三号黑体加粗；二级标题首行缩进两字符，四号黑体加粗；三级标题首行缩进两字符，小四号黑体加粗。
```
确实是“两字符”。目前的设置应该是正确的。 @0shelter0 建议你修改格式前要谨慎点。

**Comment by note286** [comment]
这种情况还算常见，比如标题是四号，正文是小四号，都是缩进两个字符，我是让标题缩进小四号的两个字符的宽度，这样美观一点，要不太突兀了。

**Comment by xkwxdyy** [comment]
> 要不太突兀了

但是如果不是选中文字的那种效果，全白背景或者打印，我觉得这个微小的差异可以完全忽略不计，或者说看不出来。

**Comment by note286** [comment]
这种离着比较近的，肉眼就会有一个虚拟的垂直线，至少我一眼就看出来，你可以不设置两个字符，直接设置缩进指定的bp即可。
