### ISSUE TITLE
扉页中 "硕士学位论文" 行间距的问题

### ISSUE THREAD

**Issue by 0shelter0** [xkwxdyy/CCNUthesis#13]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10

- TeX 发行版
  - [x] TeX Live 2022

- CCNUThesis 发行版
  - [x] v1.2.13

## 描述问题
在开启了页眉范围为所有后，即`head-scope = all,`，封面的后面一页显示如下： 

![image](https://user-images.githubusercontent.com/38009361/229270678-fd1cd3f3-f033-4a79-843b-05f309c48bc6.png)

可以看到 "硕士学位论文" 这一行段前距离有点小。我们学院官方的word显示效果如下：

![image](https://user-images.githubusercontent.com/38009361/229270896-1598e3bd-ad33-4e72-aa99-d88256a75bbf.png)

所以我的需求是：把 "硕士学位论文"  这几个字的`skip-before`和`skip-after`调整到相应的行间距。

下面是我在`cls`文件里面对`title`的设置：
```
% 标题
\cs_new:Npn \__ccnu_cover_ii_master_doctor_title:
  {
    \node at ([ shift = { (0em, 0.2\paperheight) } ]current~page~text~area.center)
      {
        \linespread{1} \fontsize{22pt}{35bp}
        \sffamily \bfseries
        \parbox [c] { \textwidth }
          {
            \centering
            \l__ccnu_info_title_tl
            % 论文题目：\parbox[t]{15em}{ \l__ccnu_info_title_tl }
          }
      };
  }
```

**Comment by sikouhjw** [comment]
无法复现你的问题，在我编译的结果中：论文题目与题目并没有换行

**Comment by 0shelter0** [comment]
我的需求描述不太对，我重新commit一下这个issue

**Comment by sikouhjw** [comment]
你需要修改的部分为
https://github.com/xkwxdyy/CCNUthesis/blob/16c8b23c10932190498f1e27e4f93eb9acd5adb2/CCNUthesis.cls#L2981-L2994
这段代码是意思是，在页面的北部，输出一个偏移量为 `(0em, 0em)` 的文本，那你只需要将
```tex
        \node [ anchor = north ] at 
          ( [ shift = { (0em, 0em) } ] current~page~text~area.north ) 
          { \zihao{1} \sffamily \bfseries 硕士学位论文 };
```
修改为
```tex
        \node [ anchor = north ] at 
          ( [ shift = { (0em, -0.05\paperheight) } ] current~page~text~area.north ) 
          { \zihao{1} \sffamily \bfseries 硕士学位论文 };
```
即可

**Comment by 0shelter0** [comment]
改了之后确实可以，效果如下：
![image](https://user-images.githubusercontent.com/38009361/229272243-a70a1b72-299c-432e-ae2e-403cdae8f577.png)

我还想调整到和下面word差不多：
![image](https://user-images.githubusercontent.com/38009361/229272314-514c3d11-7806-4a85-a0f3-417e0777db90.png)

这次应该是把 title那一行字整体往下面移动，差不多是一行的距离，求问应该怎么处理啊

**Comment by sikouhjw** [comment]
> 这次应该是把 title那一行字整体往下面移动，差不多是一行的距离，求问应该怎么处理啊

https://github.com/xkwxdyy/CCNUthesis/blob/16c8b23c10932190498f1e27e4f93eb9acd5adb2/CCNUthesis.cls#L2996-L3008

**Comment by 0shelter0** [comment]
感觉只能靠手动调整`shift = { (0em, 0.2\paperheight)`里面的值，一般`0.05\paperheight`大约是多少啊，是不是只要视觉上不冲突就可以了吧

**Comment by 0shelter0** [comment]
我已经调得差不多了，非常感谢大佬的帮助！
