### ISSUE TITLE
盲审的时候 如何删除封面以及扉页中的校名、个人信息

### ISSUE THREAD

**Issue by 0shelter0** [xkwxdyy/CCNUthesis#14]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10

- TeX 发行版
  - [x] TeX Live 2022

## 描述问题

你好，盲审的时候，需要删除论文里面所有的身份信息，包括导师、学校名字、个人信息，我的需求是删除封面以及扉页中的 学校名称。
- 封面

![image](https://user-images.githubusercontent.com/38009361/230259913-25f58389-675b-4b1d-8dfd-5866235e690f.png)

- 扉页1
![image](https://user-images.githubusercontent.com/38009361/230260296-58160d1b-9811-471e-b92a-e1828499265b.png)

- 扉页2
![image](https://user-images.githubusercontent.com/38009361/230260336-c9652ac6-f86a-451d-8ab2-0d9a65c9ca5e.png)

**Comment by sikouhjw** [comment]
https://github.com/xkwxdyy/CCNUthesis/blob/16c8b23c10932190498f1e27e4f93eb9acd5adb2/CCNUthesis.cls#L2774-L2796
https://github.com/xkwxdyy/CCNUthesis/blob/16c8b23c10932190498f1e27e4f93eb9acd5adb2/CCNUthesis.cls#L3051-L3063
https://github.com/xkwxdyy/CCNUthesis/blob/16c8b23c10932190498f1e27e4f93eb9acd5adb2/CCNUthesis.cls#L3181-L3200

**Comment by 0shelter0** [comment]
好滴，感谢

**Comment by xkwxdyy** [comment]
@0shelter0 有没有盲审的官方文件说明要去掉什么信息，我之后加一个键值来控制一下

**Comment by 0shelter0** [comment]
只有学院官方群里面的老师说了一下：
> 盲评论文需要隐去姓名，学校，导师，校徽等相关信息 ，如致谢出现人名也需要隐去；

没有正式的官方文件。

**Comment by xkwxdyy** [comment]
> 盲评论文需要隐去姓名，学校，导师，校徽等相关信息 ，如致谢出现人名也需要隐去；

我看你的需求并没有把学院去掉？

**Comment by 0shelter0** [comment]
通知里面没有提到学院，我就不去掉了

**Comment by 0shelter0** [comment]
你好，抱歉，正式的盲审格式今天才发布，通知里面需要删除【授权说明】那一页的学校信息
![image](https://user-images.githubusercontent.com/38009361/230830717-0d8bf6ec-c0aa-431c-83c5-2dcf5fa2d881.png)

求问这个该怎么删除啊

**Comment by xkwxdyy** [comment]
> 求问这个该怎么删除啊

麻烦你去问一下，如果把这一页都去掉可不可以（我觉得按照盲审的目的来说是可以的）。

因为这个声明页是通过插图的方式添加的，不行的话，就单独在做一张去掉学校名的图即可，反正都可以搞。

**Comment by 0shelter0** [comment]
你好，可以告诉我怎么把这一页删除嘛。我打算用pdf合并的方法，把这一页单独插进去。

**Comment by 0shelter0** [comment]
老师说可以直接删除这一页，不影响

**Comment by 0shelter0** [comment]
好滴 感谢大佬

**Comment by xkwxdyy** [comment]
@0shelter0 [v1.2.14](https://github.com/xkwxdyy/CCNUthesis/tree/v1.2.14) 中已更新

**Comment by 0shelter0** [comment]
收到，大佬厉害了
