### ISSUE TITLE
提交到图书馆系统要求：封面校名logo是黑色，字体调大，页眉logo黑色

### ISSUE THREAD

**Issue by 0shelter0** [xkwxdyy/CCNUthesis#16]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10

- TeX 发行版
  - [x] TeX Live 2022

## 描述问题
当论文提交到学习图书馆的时候，结果那个审核的人说：
> 校名黑色，字体调大，页眉黑色

意思是：第一页封面的校名 即`ccnulogo.png` 应该是黑色的，并且字体过小；页眉的 `masterlogo.png` 也应该是黑色的，下面是 word 版本对应的封面：

![cover](https://github.com/xkwxdyy/CCNUthesis/assets/38009361/e3171c33-9e03-4de5-a32d-81267de1edd9)

下面是 latex 生成的封面：

![xzqcover](https://github.com/xkwxdyy/CCNUthesis/assets/38009361/f0e8d091-eaf9-4032-a3d8-7964fa9fe3c2)

下面是 word 中黑色版本的 `ccnulogo`，

![ccnulogo](https://github.com/xkwxdyy/CCNUthesis/assets/38009361/f5e63c6b-d16b-463f-983f-df531b237d99)

替换彩色的 `ccnulogo.png`之后，latex 生成的封面效果如下：
![image](https://github.com/xkwxdyy/CCNUthesis/assets/38009361/0df85c8a-2fef-4f6c-b9a9-47eb21119c2b)

可以看出 logo 的还是小了一点，还需要放大。此外，我并没有找到 黑色版本的页眉`masterlogo.png` 。
综上所述，我的需求有两点：
1. 放大封面的 `ccnulogo.png`
2. 替换页眉 `masterlogo.png` 为黑色版本

请大佬帮忙再看一下哈，感激不尽！

**Comment by xkwxdyy** [comment]
https://github.com/xkwxdyy/CCNUthesis/commit/f296da08073b2c4dd1a68da3fe34c64b21fa05e8 中完成，已发布到 1.2.18 版本中。

**Comment by 0shelter0** [comment]
非常感谢
