### ISSUE TITLE
符号表后的额外空页

### ISSUE THREAD

**Issue by xkwxdyy** [xkwxdyy/CCNUthesis#4]
在 d453e15bc01e213007d8024224d3f58d3a636980 中，如果是
```latex
\documentclass[type = bachelor, version = print-bachelor-twoside]{CCNUthesis}
```
或
```latex
\documentclass[type = doctor, version = print-doctor-twoside]{CCNUthesis}
```
符号表后会多一个空白页，而硕不会

**Comment by xkwxdyy** [comment]
问题应该是出在 `twoside` 产生的空白页，在 <https://tex.stackexchange.com/questions/153057/remove-blank-pages-in-twosided-book-class-without-openany> 中查到一种解决办法是
```latex
\patchcmd { \chapter }
        { \if@openright\cleardoublepage\else\clearpage\fi }
        {}
        {}{\fail}
      \chapter { 符号表 }
```
但是 `ctex` 文类重定义了 `\chapter`，这个办法失效了。

**Comment by sikouhjw** [comment]
如果用了 `ctexheading` 的功能，可以用
```tex
\ctexset{
  chapter/break = {},
}
```

**Comment by xkwxdyy** [comment]
> 如果用了 `ctexheading` 的功能，可以用
> 
> ```
> \ctexset{
>   chapter/break = {},
> }
> ```

好像不是这个问题。我刚查了是之前设置的 `twoside` 选项传给了 `ctexbook`，考虑到教务处的本硕博都没要求奇偶不同来打印，我把 `twoside` 改成了 `oneside`。用户关于 `twoside` 的接口 只用于控制是否增加空白页。

**Comment by xkwxdyy** [comment]
> 如果用了 `ctexheading` 的功能，可以用
> 
> ```
> \ctexset{
>   chapter/break = {},
> }
> ```

感谢，不过这个 `break` 我确实也弄过接口来控制 `\ccnusetup{style/chapter-breakstyle = continuous/newpage}`

**Comment by xkwxdyy** [comment]
发现博士的必须是页码和奇偶有关，必须改成 `twoside`，看来还是得解决这个问题。

**Comment by xkwxdyy** [comment]
> 如果用了 `ctexheading` 的功能，可以用
> 
> ```
> \ctexset{
>   chapter/break = {},
> }
> ```

感谢，我又试了一下 这个好像对这个没有效果

**Comment by xkwxdyy** [comment]
我最终还是觉得双面打印的话，还是采用多一页空白的方式也不错。就接受这个效果好了
