### ISSUE TITLE
模板里中文章节(Chapter)相关问题

### ISSUE THREAD

**Issue by AstbReal** [xkwxdyy/CCNUthesis#6]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 11

- TeX 发行版
  - [x] TeX Live 2022

- CCNUThesis 版本
  - [x] V1.2.10 

## 描述问题

请在此处描述清楚您所遇到的问题：

  1. 描述出现的情况
        - 计算机学院硕士论文对于章节的要求与数统学院的样式不一致，具体内容如下：
          - 模板的chapter是阿拉伯数字形式，如，[1 2 3]
           - 计算机学院硕士论文的chapter是中文形式，如 [第一章，第二章]
           - 其他section是阿拉伯数字形式。
        
  2. 目的

        我希望能够在目录以及章节标题中`Chapter`显示出中文形式。

  3. 想法
       我自己的解决办法是，修改cls文件的关于章节模板中`\__ccnu_ctex_format_master_doctor`部分：`\__ccnu_arabic:n`改为其他用包`\usepackage{zhnumber}`来解决。但是，我对于修改cls文件没有十足把握，希望大佬能够提供一些思路或者帮助。非常感谢。

**Comment by AstbReal** [comment]
大佬，也有一个新的问题需要解决。
![image](https://user-images.githubusercontent.com/86141997/206184633-28fd01e1-e634-40a8-b0b2-669f46fcee5b.png)
如何能够实现，如上图中下划线只在文字下方，而不是每行下划线都填满呢（模板中的样子）。

**Comment by xkwxdyy** [comment]
> 大佬，也有一个新的问题需要解决。 ![image](https://user-images.githubusercontent.com/86141997/206184633-28fd01e1-e634-40a8-b0b2-669f46fcee5b.png) 如何能够实现，如上图中下划线只在文字下方，而不是每行下划线都填满呢（模板中的样子）。

这个请新开一个issue

**Comment by AstbReal** [comment]
> > 大佬，也有一个新的问题需要解决。 ![image](https://user-images.githubusercontent.com/86141997/206184633-28fd01e1-e634-40a8-b0b2-669f46fcee5b.png) 如何能够实现，如上图中下划线只在文字下方，而不是每行下划线都填满呢（模板中的样子）。
> 
> 这个请新开一个issue

好的，我下次注意。

**Comment by xkwxdyy** [comment]
@AstbReal 对了，你这是本科的还是硕博的样式？因为本科的标题应该没有华文新魏

**Comment by AstbReal** [comment]
我是计算机学院的专硕，所以修改都是基于硕博模板修改的。
