### ISSUE TITLE
标题的下划线实现“有文字部分才有下划线”

### ISSUE THREAD

**Issue by xkwxdyy** [xkwxdyy/CCNUthesis#7]
![image](https://user-images.githubusercontent.com/86141997/206184633-28fd01e1-e634-40a8-b0b2-669f46fcee5b.png)
如何能够实现，如上图中下划线只在文字下方，而不是每行下划线都填满呢（模板中的样子）。

_Originally posted by @AstbReal in https://github.com/xkwxdyy/CCNUthesis/issues/6#issuecomment-1340926700_

**Comment by xkwxdyy** [comment]
这个比现在的这个容易多了
```latex
\documentclass{ctexart}
\usepackage[]{xeCJKfntef}

\begin{document}

\begin{center}
  \begin{minipage}{12em}
    \begin{center}
      \CJKunderline*{医疗物联网中轻量级隐私保护数据共享方案的研究}
    \end{center}
    \end{minipage}
\end{center}

\end{document}
```
![image](https://user-images.githubusercontent.com/87134063/206210065-4cc3f8a3-7b28-4978-a156-38f217298722.png)

很容易实现的，我到时候加一个接口吧。

**Comment by AstbReal** [comment]
非常感谢大佬的帮助，期待新的版本。 
我有一个建议：根据不同的学院设置不同的分支或者仓库进行管理，毕竟每个学院的具体格式要求可能不尽相同。
比如计算机学院可以找CS分支。

**Comment by xkwxdyy** [comment]
> 非常感谢大佬的帮助，期待新的版本。 我有一个建议：根据不同的学院设置不同的分支或者仓库进行管理，毕竟每个学院的具体格式要求可能不尽相同。 比如计算机学院可以找CS分支。

这样会很难管理，而且这个差别不大，加个键值控制就行了

**Comment by xkwxdyy** [comment]
dev 分支的 ed21f2cb2d77f8682bac5fbed5e134ffcda4bb82 中已实现

**Comment by AstbReal** [comment]
> Owner

已看到修改内容，非常感谢您的修改。

**Comment by AstbReal** [comment]
> dev 分支的 [ed21f2c](https://github.com/xkwxdyy/CCNUthesis/commit/ed21f2cb2d77f8682bac5fbed5e134ffcda4bb82) 中已实现
已看到修改内容，非常感谢您的修改。

**Comment by AstbReal** [comment]
> dev 分支的 [ed21f2c](https://github.com/xkwxdyy/CCNUthesis/commit/ed21f2cb2d77f8682bac5fbed5e134ffcda4bb82) 中已实现

已看到修改内容，非常感谢您的修改。

**Comment by AstbReal** [comment]
> > 非常感谢大佬的帮助，期待新的版本。 我有一个建议：根据不同的学院设置不同的分支或者仓库进行管理，毕竟每个学院的具体格式要求可能不尽相同。 比如计算机学院可以找CS分支。
> 
> 这样会很难管理，而且这个差别不大，加个键值控制就行了

好，接口也挺好使用。

**Comment by xkwxdyy** [comment]
> 已看到修改内容，非常感谢您的修改。

不客气，你看看还没有其他问题
