### ISSUE TITLE
"hyperref"生成的pdf标签前面都有"zihao -4"

### ISSUE THREAD

**Issue by AstbReal** [xkwxdyy/CCNUthesis#8]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 11

- TeX 发行版
  - [x] TeX Live 2022

- CCNUThesis 版本
  - [x] V1.2.10 

## 描述问题

请在此处描述清楚您所遇到的问题：

  1. 描述出现的情况
        - 在进行`xelatex -> biber -> xelatex*2`后，生成的pdf便签会多一个`zihao -4`,具体内容如下图:
           
![image](https://user-images.githubusercontent.com/86141997/206347037-f81568de-db24-45c7-bd8f-fd02d9ad40aa.png)

        
  2. 目的

        我希望能够去掉这些`zihao -4`。

  3. 想法
       已解决，将`CCNUthesis.cls`文件中的`\__ccnu_tocline_master`里的`zihao -4`删除，再重新`xelatex -> biber -> xelatex*2`即可修复。这样操作不知道有没有什么问题。

**Comment by 0shelter0** [comment]
我试了，结果生成的目录有问题，向下面这样
![image](https://user-images.githubusercontent.com/38009361/229118567-bf459d36-e033-47d6-9c3f-dfa5a1e0d5c9.png)

不知道你最后的方法是什么

**Comment by sikouhjw** [comment]
他的意思是将
https://github.com/xkwxdyy/CCNUthesis/blob/16c8b23c10932190498f1e27e4f93eb9acd5adb2/CCNUthesis.cls#L3438-L3462
改为
```tex
\cs_new:Npn \__ccnu_tocline_master:
  {
    \keys_set:nn { ctex }
      {
        % 目录深度：到 section
        tocdepth = 2 ,
        % 目录标题
        contentsname   = \c__ccnu_name_toc_tl,
        chapter / tocline =
          {
            \normalfont \bfseries \texorpdfstring{ \zihao{-4} }{  }
            \CTEXnumberline {##1} ##2
          },
        section / tocline =
          {
            \normalfont \texorpdfstring{ \zihao{-4} }{  }
            \CTEXnumberline {##1} ##2
          },
        subsection / tocline =
          {
            \normalfont \texorpdfstring{ \zihao{-4} }{  }
            \CTEXnumberline {##1} ##2
          }
      }
  }
```

**Comment by 0shelter0** [comment]
替换之后就好了，在pdf阅读器里面也可以正常显示书签了，感谢大佬！！！

**Comment by xkwxdyy** [comment]
[v1.2.14](https://github.com/xkwxdyy/CCNUthesis/tree/v1.2.14) 中已修复
